//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stadium
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stadiumDB : DbContext
    {
        public stadiumDB()
            : base("name=stadiumDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<reserv> reservs { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<stadium> stadia { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
