//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stadium
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserv
    {
        public int id { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> stadiumID { get; set; }
        public Nullable<int> clientID { get; set; }
        public Nullable<System.DateTime> reservdate { get; set; }
        public Nullable<System.DateTime> reservdeadlien { get; set; }
        public Nullable<double> price { get; set; }
    
        public virtual client client { get; set; }
        public virtual room room { get; set; }
        public virtual stadium stadium { get; set; }
    }
}
